apiVersion: v1
kind: Service
metadata:
  name: hackathon-server
  namespace: diagnostics
spec:
  selector:
    app: hackathon-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: NodePort
